#!/bin/bash
whoami=($user)
clear
echo -e "Welcome to:"
echo -e "\n \ \ / /__ _  _|   \ _____ __ ___ _  \n  \ V / _ \ || | |) / _ \ V  V / ' \ \n   | |\   /\ , |   /\   /\ /\ /| || |\n"
echo -e "A program by Elodie Tscharke \\n \\n"
echo -e "Main menu:"
echo -e "\\n1. Download a video \\n0. Exit"
printf ": "
read main
if [[ "$main" == "0" ]];
then
  exit
fi

if [[ "$main" == "1" ]];
then
  clear
  echo -e "Enter the part of the url that comes after https://www.youtube.com/watch?v= e.g. dQw4w9WgXcQ"
  printf ": "
  read yt
  clear
  echo -e "Enter name of desired output file (do NOT include file extensions and do NOT include ANY spaces) format will be {yourfilenamehere}.mp4"
  printf ": "
  read name
  echo -e "If you get any errors then either your connection isn't working or you entered a bad url \\n \\n \\n \\n \\n"
  echo -e "[*]Fetching url ...[*] \\n \\n"
  wget -O paage.tmp https://www.youtube.com/watch?v=${yt}
  echo -e "\\n \\n \\n[*]Downloading video ...[*]\\n \\n"
  youtube-dl $yt -f mp4 --hls-use-mpegts --external-downloader wget --id
  echo -e "\\n \\n \\n[*]Finished Downloading[*]\\n \\n"
  echo -e "[*]Fixing filenames ...[*] \\n \\n"
  mv ${yt}.mp4 ${name}.mp4
  echo -e "\\n \\n \\n[*]Cleaning Up ...[*]\\n \\n"
  rm paage.tmp
  echo -e "\\n \\n[*]Done[*]"
  echo -e "\\n \\n[*]Press [ENTER] to Continue[*]"
  read whogivesashiteeee
  youdown
fi
